update buku set qty= '5' where id='1'  ;
update buku set qty= '3' where id='2'  ;
update buku set qty= '3' where id='3'  ;
update buku set qty= '3' where id='4'  ;
update buku set qty= '3' where id='5'  ;
update buku set qty= '3' where id='6'  ;
update buku set qty= '3' where id='7'  ;
update buku set qty= '3' where id='8'  ;
update buku set qty= '3' where id='9'  ;
update buku set qty= '3' where id='10' ;
update buku set qty= '3' where id='11' ;
update buku set qty= '3' where id='12' ;
update buku set qty= '3' where id='13' ;
update buku set qty= '3' where id='14' ;
update buku set qty= '0' where id='15' ;
update buku set qty= '0' where id='16' ;
update buku set qty= '2' where id='17' ;
update buku set qty= '2' where id='18' ;
update buku set qty= '2' where id='19' ;
update buku set qty= '2' where id='20' ;
update buku set qty= '2' where id='21' ;
update buku set qty= '5' where id='22' ;
update buku set qty= '5' where id='23' ;
update buku set qty= '5' where id='24' ;
update buku set qty= '5' where id='25' ;
update buku set qty= '5' where id='26' ;
update buku set qty= '5' where id='27' ;
update buku set qty= '5' where id='28' ;
update buku set qty= '5' where id='29' ;
update buku set qty= '5' where id='30' ;
update buku set qty= '5' where id='31' ;
update buku set qty= '5' where id='32' ;
update buku set qty= '5' where id='33' ;
update buku set qty= '5' where id='34' ;
update buku set qty= '0' where id='35' ;
update buku set qty= '0' where id='36' ;
update buku set qty= '0' where id='37' ;
update buku set qty= '0' where id='38' ;
update buku set qty= '3' where id='39' ;
update buku set qty= '3' where id='40' ;
update buku set qty= '3' where id='41' ;
update buku set qty= '3' where id='42' ;
update buku set qty= '2' where id='43' ;
update buku set qty= '2' where id='44' ;
update buku set qty= '2' where id='45' ;
update buku set qty= '2' where id='46' ;
update buku set qty= '2' where id='47' ;
update buku set qty= '0' where id='48' ;
update buku set qty= '0' where id='49' ;
update buku set qty= '0' where id='50' ;
update buku set qty= '0' where id='51' ;
update buku set qty= '0' where id='52' ;
update buku set qty= '6' where id='53' ;
update buku set qty= '6' where id='54' ;
update buku set qty= '6' where id='55' ;
update buku set qty= '6' where id='56' ;
update buku set qty= '6' where id='57' ;
update buku set qty= '0' where id='58' ;
update buku set qty= '0' where id='59' ;
update buku set qty= '2' where id='60' ;
update buku set qty= '2' where id='61' ;
update buku set qty= '2' where id='62' ;
update buku set qty= '1' where id='63' ;
update buku set qty= '1' where id='64' ;
update buku set qty= '1' where id='65' ;
update buku set qty= '1' where id='66' ;
update buku set qty= '1' where id='67' ;
update buku set qty= '0' where id='68' ;
update buku set qty= '0' where id='69' ;
update buku set qty= '0' where id='70' ;
update buku set qty= '0' where id='71' ;
update buku set qty= '0' where id='72' ;
update buku set qty= '3' where id='73' ;
update buku set qty= '3' where id='74' ;
update buku set qty= '3' where id='75' ;
update buku set qty= '3' where id='76' ;
update buku set qty= '3' where id='77' ;
update buku set qty= '0' where id='78' ;
update buku set qty= '0' where id='79' ;
update buku set qty= '0' where id='80' ;
update buku set qty= '0' where id='81' ;
update buku set qty= '3' where id='82' ;
update buku set qty= '3' where id='83' ;
update buku set qty= '3' where id='84' ;
update buku set qty= '3' where id='85' ;
update buku set qty= '3' where id='86' ;
update buku set qty= '0' where id='87' ;
update buku set qty= '0' where id='88' ;
update buku set qty= '0' where id='89' ;
update buku set qty= '8' where id='90' ;
update buku set qty= '8' where id='91' ;
update buku set qty= '8' where id='92' ;
update buku set qty= '8' where id='93' ;
update buku set qty= '8' where id='94' ;
update buku set qty= '0' where id='95' ;
update buku set qty= '0' where id='96' ;
update buku set qty= '0' where id='97' ;
update buku set qty= '0' where id='98' ;
update buku set qty= '0' where id='99' ;
update buku set qty= '3' where id='100';
update buku set qty= '3' where id='101';
update buku set qty= '2' where id='102';
update buku set qty= '0' where id='103';
update buku set qty= '3' where id='104';
update buku set qty= '0' where id='105';
update buku set qty= '1' where id='106';
update buku set qty= '1' where id='107';
update buku set qty= '4' where id='108';
update buku set qty= '1' where id='109';
update buku set qty= '0' where id='110';
update buku set qty= '1' where id='111';
update buku set qty= '2' where id='112';
update buku set qty= '3' where id='113';
update buku set qty= '1' where id='114';
update buku set qty= '3' where id='115';
update buku set qty= '0' where id='116';
update buku set qty= '4' where id='117';
update buku set qty= '4' where id='118';
update buku set qty= '2' where id='119';
update buku set qty= '2' where id='120';
update buku set qty= '3' where id='121';
update buku set qty= '3' where id='122';
update buku set qty= '3' where id='123';
update buku set qty= '3' where id='124';
update buku set qty= '1' where id='125';
update buku set qty= '0' where id='126';
update buku set qty= '3' where id='127';
update buku set qty= '1' where id='128';
update buku set qty= '3' where id='129';
update buku set qty= '1' where id='130';
update buku set qty= '0' where id='131';
update buku set qty= '1' where id='132';
update buku set qty= '1' where id='133';
update buku set qty= '4' where id='134';
update buku set qty= '4' where id='135';
update buku set qty= '2' where id='136';
update buku set qty= '2' where id='137';
update buku set qty= '4' where id='138';
update buku set qty= '0' where id='139';
update buku set qty= '3' where id='140';
update buku set qty= '4' where id='141';
update buku set qty= '3' where id='142';
update buku set qty= '3' where id='143';
update buku set qty= '1' where id='144';
update buku set qty= '0' where id='145';
update buku set qty= '2' where id='146';
update buku set qty= '1' where id='147';
update buku set qty= '0' where id='148';
update buku set qty= '3' where id='149';
update buku set qty= '3' where id='150';
update buku set qty= '3' where id='151';
update buku set qty= '0' where id='152';
update buku set qty= '1' where id='153';
update buku set qty= '0' where id='154';
update buku set qty= '2' where id='155';
update buku set qty= '4' where id='156';
update buku set qty= '4' where id='157';
update buku set qty= '4' where id='158';
update buku set qty= '2' where id='159';
update buku set qty= '0' where id='160';
update buku set qty= '0' where id='161';
update buku set qty= '3' where id='162';
update buku set qty= '3' where id='163';
update buku set qty= '0' where id='164';
update buku set qty= '4' where id='165';
update buku set qty= '1' where id='166';
update buku set qty= '1' where id='167';
update buku set qty= '1' where id='168';
update buku set qty= '4' where id='169';
update buku set qty= '0' where id='170';
update buku set qty= '3' where id='171';
update buku set qty= '0' where id='172';
update buku set qty= '3' where id='173';
update buku set qty= '1' where id='174';
update buku set qty= '4' where id='175';
update buku set qty= '3' where id='176';
update buku set qty= '1' where id='177';
update buku set qty= '4' where id='178';
update buku set qty= '1' where id='179';
update buku set qty= '0' where id='180';
update buku set qty= '0' where id='181';
update buku set qty= '0' where id='182';
update buku set qty= '0' where id='183';
update buku set qty= '0' where id='184';
update buku set qty= '1' where id='185';
update buku set qty= '2' where id='186';
update buku set qty= '2' where id='187';
update buku set qty= '1' where id='188';
update buku set qty= '2' where id='189';
update buku set qty= '1' where id='190';
update buku set qty= '1' where id='191';
update buku set qty= '3' where id='192';
update buku set qty= '3' where id='193';
update buku set qty= '3' where id='194';
update buku set qty= '2' where id='195';
update buku set qty= '4' where id='196';
update buku set qty= '0' where id='197';
update buku set qty= '1' where id='198';
update buku set qty= '0' where id='199';
update buku set qty= '2' where id='200';
update buku set qty= '1' where id='201';
update buku set qty= '3' where id='202';
update buku set qty= '4' where id='203';
update buku set qty= '2' where id='204';
update buku set qty= '4' where id='205';
update buku set qty= '3' where id='206';
update buku set qty= '2' where id='207';
update buku set qty= '2' where id='208';
update buku set qty= '3' where id='209';
update buku set qty= '1' where id='210';
update buku set qty= '1' where id='211';
update buku set qty= '3' where id='212';
update buku set qty= '4' where id='213';
update buku set qty= '1' where id='214';
update buku set qty= '3' where id='215';
update buku set qty= '4' where id='216';
update buku set qty= '0' where id='217';
update buku set qty= '2' where id='218';
update buku set qty= '0' where id='219';
update buku set qty= '1' where id='220';
update buku set qty= '4' where id='221';
update buku set qty= '3' where id='222';
update buku set qty= '2' where id='223';
update buku set qty= '4' where id='224';
update buku set qty= '0' where id='225';
update buku set qty= '2' where id='226';
update buku set qty= '4' where id='227';
update buku set qty= '0' where id='228';
update buku set qty= '2' where id='229';
update buku set qty= '1' where id='230';
update buku set qty= '1' where id='231';
update buku set qty= '0' where id='232';
update buku set qty= '4' where id='233';
update buku set qty= '2' where id='234';
update buku set qty= '2' where id='235';
update buku set qty= '0' where id='236';
update buku set qty= '2' where id='237';
update buku set qty= '2' where id='238';
update buku set qty= '2' where id='239';
update buku set qty= '0' where id='240';
update buku set qty= '1' where id='241';
update buku set qty= '0' where id='242';
update buku set qty= '3' where id='243';
update buku set qty= '1' where id='244';
update buku set qty= '4' where id='245';
update buku set qty= '3' where id='246';
update buku set qty= '0' where id='247';
update buku set qty= '0' where id='248';
update buku set qty= '1' where id='249';
update buku set qty= '1' where id='250';
update buku set qty= '3' where id='251';
update buku set qty= '3' where id='252';
update buku set qty= '1' where id='253';
update buku set qty= '1' where id='254';
update buku set qty= '1' where id='255';
update buku set qty= '1' where id='256';
update buku set qty= '1' where id='257';
update buku set qty= '0' where id='258';
update buku set qty= '3' where id='259';
update buku set qty= '4' where id='260';
update buku set qty= '0' where id='261';
update buku set qty= '2' where id='262';
update buku set qty= '2' where id='263';
update buku set qty= '2' where id='264';
update buku set qty= '2' where id='265';
update buku set qty= '2' where id='266';
update buku set qty= '1' where id='267';
update buku set qty= '0' where id='268';
update buku set qty= '4' where id='269';
update buku set qty= '0' where id='270';
update buku set qty= '0' where id='271';
update buku set qty= '4' where id='272';
update buku set qty= '1' where id='273';
update buku set qty= '3' where id='274';
update buku set qty= '2' where id='275';
update buku set qty= '3' where id='276';
update buku set qty= '1' where id='277';
update buku set qty= '0' where id='278';
update buku set qty= '4' where id='279';
update buku set qty= '2' where id='280';
update buku set qty= '1' where id='281';
update buku set qty= '3' where id='282';
update buku set qty= '1' where id='283';
update buku set qty= '1' where id='284';
update buku set qty= '2' where id='285';
update buku set qty= '0' where id='286';
update buku set qty= '1' where id='287';
update buku set qty= '3' where id='288';
update buku set qty= '4' where id='289';
update buku set qty= '0' where id='290';
update buku set qty= '1' where id='291';
update buku set qty= '2' where id='292';
update buku set qty= '2' where id='293';
update buku set qty= '2' where id='294';
update buku set qty= '1' where id='295';
update buku set qty= '0' where id='296';
update buku set qty= '0' where id='297';
update buku set qty= '0' where id='298';
update buku set qty= '4' where id='299';
update buku set qty= '3' where id='300';
update buku set qty= '1' where id='301';
update buku set qty= '3' where id='302';
update buku set qty= '2' where id='303';
update buku set qty= '3' where id='304';
update buku set qty= '1' where id='305';
update buku set qty= '2' where id='306';
update buku set qty= '4' where id='307';
update buku set qty= '2' where id='308';
update buku set qty= '4' where id='309';
update buku set qty= '0' where id='310';
update buku set qty= '1' where id='311';
update buku set qty= '2' where id='312';
update buku set qty= '3' where id='313';
update buku set qty= '0' where id='314';
update buku set qty= '3' where id='315';
update buku set qty= '0' where id='316';
update buku set qty= '2' where id='317';
update buku set qty= '1' where id='318';
update buku set qty= '2' where id='319';
update buku set qty= '2' where id='320';
update buku set qty= '3' where id='321';
update buku set qty= '1' where id='322';
update buku set qty= '4' where id='323';
update buku set qty= '4' where id='324';
update buku set qty= '0' where id='325';
update buku set qty= '2' where id='326';
update buku set qty= '1' where id='327';
update buku set qty= '4' where id='328';
update buku set qty= '2' where id='329';
update buku set qty= '1' where id='330';
update buku set qty= '4' where id='331';
update buku set qty= '4' where id='332';
update buku set qty= '0' where id='333';
update buku set qty= '3' where id='334';
update buku set qty= '4' where id='335';
update buku set qty= '2' where id='336';
update buku set qty= '0' where id='337';
update buku set qty= '3' where id='338';
update buku set qty= '1' where id='339';
update buku set qty= '4' where id='340';
update buku set qty= '1' where id='341';
update buku set qty= '2' where id='342';
update buku set qty= '2' where id='343';
update buku set qty= '1' where id='344';
update buku set qty= '4' where id='345';
update buku set qty= '1' where id='346';
update buku set qty= '2' where id='347';
update buku set qty= '2' where id='348';
update buku set qty= '3' where id='349';
update buku set qty= '2' where id='350';
update buku set qty= '2' where id='351';
update buku set qty= '0' where id='352';
update buku set qty= '0' where id='353';
update buku set qty= '0' where id='354';
update buku set qty= '0' where id='355';
update buku set qty= '4' where id='356';
update buku set qty= '2' where id='357';
update buku set qty= '1' where id='358';
update buku set qty= '3' where id='359';
update buku set qty= '3' where id='360';
update buku set qty= '3' where id='361';
update buku set qty= '3' where id='362';
update buku set qty= '3' where id='363';
update buku set qty= '0' where id='364';
update buku set qty= '3' where id='365';
update buku set qty= '3' where id='366';
update buku set qty= '3' where id='367';
update buku set qty= '4' where id='368';
update buku set qty= '2' where id='369';
update buku set qty= '2' where id='370';
update buku set qty= '4' where id='371';
update buku set qty= '4' where id='372';
update buku set qty= '3' where id='373';
update buku set qty= '1' where id='374';
update buku set qty= '0' where id='375';
update buku set qty= '1' where id='376';
update buku set qty= '1' where id='377';
update buku set qty= '4' where id='378';
update buku set qty= '0' where id='379';
update buku set qty= '0' where id='380';
update buku set qty= '0' where id='381';
update buku set qty= '2' where id='382';
update buku set qty= '0' where id='383';
update buku set qty= '4' where id='384';
update buku set qty= '1' where id='385';
update buku set qty= '1' where id='386';
update buku set qty= '3' where id='387';
update buku set qty= '0' where id='388';
update buku set qty= '3' where id='389';
update buku set qty= '1' where id='390';
update buku set qty= '3' where id='391';
update buku set qty= '3' where id='392';
update buku set qty= '4' where id='393';
update buku set qty= '4' where id='394';
update buku set qty= '1' where id='395';
update buku set qty= '3' where id='396';
update buku set qty= '2' where id='397';
update buku set qty= '2' where id='398';
update buku set qty= '3' where id='399';
update buku set qty= '3' where id='400';
update buku set qty= '3' where id='401';
update buku set qty= '4' where id='402';
update buku set qty= '2' where id='403';
update buku set qty= '4' where id='404';
update buku set qty= '4' where id='405';
update buku set qty= '0' where id='406';
update buku set qty= '0' where id='407';
update buku set qty= '0' where id='408';
update buku set qty= '3' where id='409';
update buku set qty= '2' where id='410';
update buku set qty= '3' where id='411';
update buku set qty= '4' where id='412';
update buku set qty= '1' where id='413';
update buku set qty= '4' where id='414';
update buku set qty= '2' where id='415';
update buku set qty= '4' where id='416';
update buku set qty= '1' where id='417';
update buku set qty= '2' where id='418';
update buku set qty= '2' where id='419';
update buku set qty= '4' where id='420';
update buku set qty= '2' where id='421';
update buku set qty= '1' where id='422';
update buku set qty= '1' where id='423';
update buku set qty= '4' where id='424';
update buku set qty= '4' where id='425';
update buku set qty= '0' where id='426';
update buku set qty= '2' where id='427';
update buku set qty= '4' where id='428';
update buku set qty= '2' where id='429';
update buku set qty= '0' where id='430';
update buku set qty= '4' where id='431';
update buku set qty= '2' where id='432';
update buku set qty= '2' where id='433';
update buku set qty= '4' where id='434';
update buku set qty= '3' where id='435';
update buku set qty= '1' where id='436';
update buku set qty= '4' where id='437';
update buku set qty= '0' where id='438';
update buku set qty= '4' where id='439';
update buku set qty= '4' where id='440';
update buku set qty= '0' where id='441';
update buku set qty= '4' where id='442';
update buku set qty= '0' where id='443';
update buku set qty= '2' where id='444';
update buku set qty= '0' where id='445';
update buku set qty= '1' where id='446';
update buku set qty= '3' where id='447';
update buku set qty= '0' where id='448';
update buku set qty= '0' where id='449';
update buku set qty= '0' where id='450';
update buku set qty= '4' where id='451';
update buku set qty= '3' where id='452';
update buku set qty= '4' where id='453';
update buku set qty= '1' where id='454';
update buku set qty= '4' where id='455';
update buku set qty= '2' where id='456';
update buku set qty= '0' where id='457';
update buku set qty= '0' where id='458';
update buku set qty= '2' where id='459';
update buku set qty= '0' where id='460';
update buku set qty= '4' where id='461';
update buku set qty= '4' where id='462';
update buku set qty= '2' where id='463';
update buku set qty= '0' where id='464';
update buku set qty= '3' where id='465';
update buku set qty= '2' where id='466';
update buku set qty= '0' where id='467';
update buku set qty= '0' where id='468';
update buku set qty= '4' where id='469';
update buku set qty= '3' where id='470';
update buku set qty= '4' where id='471';
update buku set qty= '4' where id='472';
update buku set qty= '1' where id='473';
update buku set qty= '3' where id='474';
update buku set qty= '3' where id='475';
update buku set qty= '2' where id='476';
update buku set qty= '0' where id='477';
update buku set qty= '0' where id='478';
update buku set qty= '4' where id='479';
update buku set qty= '2' where id='480';
update buku set qty= '4' where id='481';
update buku set qty= '0' where id='482';
update buku set qty= '0' where id='483';
update buku set qty= '4' where id='484';
update buku set qty= '1' where id='485';
update buku set qty= '1' where id='486';
update buku set qty= '3' where id='487';
update buku set qty= '1' where id='488';
update buku set qty= '4' where id='489';
update buku set qty= '3' where id='490';
update buku set qty= '1' where id='491';
update buku set qty= '4' where id='492';
update buku set qty= '4' where id='493';
update buku set qty= '4' where id='494';
update buku set qty= '1' where id='495';
update buku set qty= '0' where id='496';
update buku set qty= '4' where id='497';
update buku set qty= '3' where id='498';
update buku set qty= '3' where id='499';
update buku set qty= '2' where id='500';
update buku set qty= '0' where id='501';
update buku set qty= '3' where id='502';
update buku set qty= '0' where id='503';
update buku set qty= '2' where id='504';
update buku set qty= '2' where id='505';
update buku set qty= '2' where id='506';
update buku set qty= '0' where id='507';
update buku set qty= '4' where id='508';
update buku set qty= '3' where id='509';
update buku set qty= '3' where id='510';
update buku set qty= '3' where id='511';
update buku set qty= '0' where id='512';
update buku set qty= '3' where id='513';
update buku set qty= '4' where id='514';
update buku set qty= '3' where id='515';
update buku set qty= '2' where id='516';
update buku set qty= '4' where id='517';
update buku set qty= '2' where id='518';
update buku set qty= '3' where id='519';
update buku set qty= '3' where id='520';
update buku set qty= '2' where id='521';
update buku set qty= '0' where id='522';
update buku set qty= '0' where id='523';
update buku set qty= '2' where id='524';
update buku set qty= '2' where id='525';
update buku set qty= '1' where id='526';
update buku set qty= '3' where id='527';
update buku set qty= '1' where id='528';
update buku set qty= '1' where id='529';
update buku set qty= '2' where id='530';
update buku set qty= '4' where id='531';
update buku set qty= '0' where id='532';
update buku set qty= '2' where id='533';
update buku set qty= '0' where id='534';
update buku set qty= '3' where id='535';
update buku set qty= '0' where id='536';
update buku set qty= '3' where id='537';
update buku set qty= '3' where id='538';
update buku set qty= '0' where id='539';
update buku set qty= '0' where id='540';
update buku set qty= '3' where id='541';
update buku set qty= '0' where id='542';
update buku set qty= '4' where id='543';
update buku set qty= '4' where id='544';
update buku set qty= '3' where id='545';
update buku set qty= '2' where id='546';
update buku set qty= '4' where id='547';
update buku set qty= '0' where id='548';
update buku set qty= '4' where id='549';
update buku set qty= '3' where id='550';
update buku set qty= '3' where id='551';
update buku set qty= '1' where id='552';
update buku set qty= '1' where id='553';
update buku set qty= '1' where id='554';
update buku set qty= '0' where id='555';
update buku set qty= '0' where id='556';
update buku set qty= '1' where id='557';
update buku set qty= '4' where id='558';
update buku set qty= '2' where id='559';
update buku set qty= '3' where id='560';
update buku set qty= '4' where id='561';
update buku set qty= '1' where id='562';
update buku set qty= '3' where id='563';
update buku set qty= '0' where id='564';
update buku set qty= '2' where id='565';
update buku set qty= '1' where id='566';
update buku set qty= '4' where id='567';
update buku set qty= '4' where id='568';
update buku set qty= '1' where id='569';
update buku set qty= '1' where id='570';
update buku set qty= '1' where id='571';
update buku set qty= '2' where id='572';
update buku set qty= '2' where id='573';
update buku set qty= '4' where id='574';
update buku set qty= '2' where id='575';
update buku set qty= '3' where id='576';
update buku set qty= '1' where id='577';
update buku set qty= '3' where id='578';
update buku set qty= '3' where id='579';
update buku set qty= '1' where id='580';
update buku set qty= '4' where id='581';
update buku set qty= '1' where id='582';
update buku set qty= '0' where id='583';
update buku set qty= '3' where id='584';
update buku set qty= '0' where id='585';
update buku set qty= '0' where id='586';
update buku set qty= '3' where id='587';
update buku set qty= '0' where id='588';
update buku set qty= '0' where id='589';
update buku set qty= '2' where id='590';
update buku set qty= '3' where id='591';
update buku set qty= '1' where id='592';
update buku set qty= '2' where id='593';
update buku set qty= '2' where id='594';
update buku set qty= '2' where id='595';
update buku set qty= '3' where id='596';
update buku set qty= '2' where id='597';
update buku set qty= '1' where id='598';
update buku set qty= '0' where id='599';
update buku set qty= '0' where id='600';
update buku set qty= '0' where id='601';
update buku set qty= '3' where id='602';
update buku set qty= '0' where id='603';
update buku set qty= '4' where id='604';
update buku set qty= '1' where id='605';
update buku set qty= '2' where id='606';
update buku set qty= '4' where id='607';
update buku set qty= '2' where id='608';
update buku set qty= '0' where id='609';
update buku set qty= '0' where id='610';
update buku set qty= '3' where id='611';
update buku set qty= '4' where id='612';
update buku set qty= '1' where id='613';
update buku set qty= '4' where id='614';
update buku set qty= '0' where id='615';
update buku set qty= '4' where id='616';
update buku set qty= '1' where id='617';
update buku set qty= '4' where id='618';
update buku set qty= '0' where id='619';
update buku set qty= '1' where id='620';
update buku set qty= '3' where id='621';
update buku set qty= '3' where id='622';
update buku set qty= '4' where id='623';
update buku set qty= '1' where id='624';
update buku set qty= '0' where id='625';
update buku set qty= '4' where id='626';
update buku set qty= '1' where id='627';
update buku set qty= '3' where id='628';
update buku set qty= '1' where id='629';
update buku set qty= '1' where id='630';
update buku set qty= '3' where id='631';
update buku set qty= '4' where id='632';
update buku set qty= '2' where id='633';
update buku set qty= '3' where id='634';
update buku set qty= '1' where id='635';
update buku set qty= '3' where id='636';
update buku set qty= '4' where id='637';
update buku set qty= '2' where id='638';
update buku set qty= '2' where id='639';
update buku set qty= '3' where id='640';
update buku set qty= '1' where id='641';
update buku set qty= '3' where id='642';
update buku set qty= '0' where id='643';
update buku set qty= '1' where id='644';
update buku set qty= '0' where id='645';
update buku set qty= '2' where id='646';
update buku set qty= '0' where id='647';
update buku set qty= '4' where id='648';
update buku set qty= '0' where id='649';
update buku set qty= '3' where id='650';
update buku set qty= '4' where id='651';
update buku set qty= '2' where id='652';
update buku set qty= '3' where id='653';
update buku set qty= '4' where id='654';
update buku set qty= '4' where id='655';
update buku set qty= '3' where id='656';
update buku set qty= '2' where id='657';
update buku set qty= '3' where id='658';
update buku set qty= '3' where id='659';
update buku set qty= '4' where id='660';
update buku set qty= '1' where id='661';
update buku set qty= '1' where id='662';
update buku set qty= '3' where id='663';
update buku set qty= '0' where id='664';
update buku set qty= '3' where id='665';
update buku set qty= '1' where id='666';
update buku set qty= '4' where id='667';
update buku set qty= '3' where id='668';
update buku set qty= '3' where id='669';
update buku set qty= '1' where id='670';
update buku set qty= '0' where id='671';
update buku set qty= '0' where id='672';
update buku set qty= '3' where id='673';
update buku set qty= '2' where id='674';
update buku set qty= '3' where id='675';
update buku set qty= '2' where id='676';
update buku set qty= '4' where id='677';
update buku set qty= '3' where id='678';
update buku set qty= '0' where id='679';
update buku set qty= '3' where id='680';
update buku set qty= '3' where id='681';
update buku set qty= '4' where id='682';
update buku set qty= '3' where id='683';
update buku set qty= '3' where id='684';
update buku set qty= '4' where id='685';
update buku set qty= '4' where id='686';
update buku set qty= '4' where id='687';
update buku set qty= '4' where id='688';
update buku set qty= '3' where id='689';
update buku set qty= '4' where id='690';
update buku set qty= '3' where id='691';
update buku set qty= '4' where id='692';
update buku set qty= '2' where id='693';
update buku set qty= '3' where id='694';
update buku set qty= '1' where id='695';
update buku set qty= '2' where id='696';
update buku set qty= '1' where id='697';
update buku set qty= '1' where id='698';
update buku set qty= '0' where id='699';
update buku set qty= '3' where id='700';
update buku set qty= '0' where id='701';
update buku set qty= '0' where id='702';
update buku set qty= '4' where id='703';
update buku set qty= '1' where id='704';
update buku set qty= '0' where id='705';
update buku set qty= '0' where id='706';
update buku set qty= '0' where id='707';
update buku set qty= '1' where id='708';
update buku set qty= '0' where id='709';
update buku set qty= '3' where id='710';
update buku set qty= '4' where id='711';
update buku set qty= '0' where id='712';
update buku set qty= '0' where id='713';
update buku set qty= '1' where id='714';
update buku set qty= '0' where id='715';
update buku set qty= '0' where id='716';
update buku set qty= '3' where id='717';
update buku set qty= '3' where id='718';
update buku set qty= '0' where id='719';
update buku set qty= '2' where id='720';
update buku set qty= '3' where id='721';
update buku set qty= '3' where id='722';
update buku set qty= '2' where id='723';
update buku set qty= '4' where id='724';
update buku set qty= '0' where id='725';
update buku set qty= '0' where id='726';
update buku set qty= '3' where id='727';
update buku set qty= '0' where id='728';
update buku set qty= '3' where id='729';
update buku set qty= '1' where id='730';
update buku set qty= '4' where id='731';
update buku set qty= '0' where id='732';
update buku set qty= '1' where id='733';
update buku set qty= '4' where id='734';
update buku set qty= '4' where id='735';
update buku set qty= '3' where id='736';
update buku set qty= '2' where id='737';
update buku set qty= '1' where id='738';
update buku set qty= '1' where id='739';
update buku set qty= '4' where id='740';
update buku set qty= '0' where id='741';
update buku set qty= '1' where id='742';
update buku set qty= '3' where id='743';
update buku set qty= '4' where id='744';
update buku set qty= '2' where id='745';
update buku set qty= '4' where id='746';
update buku set qty= '1' where id='747';
update buku set qty= '2' where id='748';
update buku set qty= '4' where id='749';
update buku set qty= '3' where id='750';
update buku set qty= '2' where id='751';
update buku set qty= '2' where id='752';
update buku set qty= '4' where id='753';
update buku set qty= '4' where id='754';
update buku set qty= '4' where id='755';
update buku set qty= '0' where id='756';
update buku set qty= '2' where id='757';
update buku set qty= '2' where id='758';
update buku set qty= '1' where id='759';
update buku set qty= '3' where id='760';
update buku set qty= '3' where id='761';
update buku set qty= '1' where id='762';
update buku set qty= '0' where id='763';
update buku set qty= '0' where id='764';
update buku set qty= '3' where id='765';
update buku set qty= '0' where id='766';